import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {


  const Sidebar = () => {
    return (
      <div className="sidebar">
        <h1>Home</h1>
      </div>
    );
  };

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
      <div className="mainContent">
        <iframe width='100%' height='100%' src="https://experience.arcgis.com/experience/215881dc1f594f6da5e566efbdc5d7d4/"></iframe>
      </div>

    </div>
  )
}
