import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Map2 from '../functions/map2'

export default function Home() {


  const Sidebar = () => {
    return (
      <div className="sidebar">
        <h1>Home</h1>
      </div>
    );
  };

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
      <div className="mainContent">
        <Map2 />
      </div>

    </div>
  )
}
